### ISSUE TITLE
numpy version incompatible

### ISSUE THREAD

**Issue by SylviaObserver** [tardis-sn/tardis#1152]
Hi,

I am also installing TARDIS for the first time, and I installed it using Anaconda 3.

Following the quickstart instructions, after running the below line in terminal:

```python
 sim = run_tardis('tardis_example.yml')


#I received the error:

ValueError: numpy.ufunc size changed, may indicate binary incompatibility. 

Please tell me which numpy version for python3 is compatible with tardis.
(I use macOS Catalina 10.15.1)

**Comment by marxwillia** [comment]
Hi @SylviaObserver, are you creating the TARDIS conda environment and activating it before using TARDIS?  The numpy version should be fixed to be compatible with TARDIS.  Installation instructions can be found here:  https://tardis-sn.github.io/tardis/installation.html

**Comment by SylviaObserver** [comment]
Yes,I activate TARDIS conda environment first and then import tardis with python3. Besides, my numpy version is 1.15 as it in  environment definition file. I'm relatively inexperienced so thanks for your help.

**Comment by wkerzendorf** [comment]
@SylviaObserver - if you could provide us a minimum working example - so editing your issue to include the precise commands you type on the command-line. That will help us to try that on our systems as well and replicate the issue and hopefully help fix it.

**Comment by SylviaObserver** [comment]
OK! Thanks so much.
````python
source activate tardis
python
from tardis import run_tardis
sim = run_tardis('tardis_example.yml')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sacredmi/anaconda3/envs/tardis/lib/python3.6/site-packages/tardis/base.py", line 24, in run_tardis
    from tardis.simulation import Simulation
  File "/Users/sacredmi/anaconda3/envs/tardis/lib/python3.6/site-packages/tardis/simulation/__init__.py", line 1, in <module>
    from tardis.simulation.base import Simulation
  File "/Users/sacredmi/anaconda3/envs/tardis/lib/python3.6/site-packages/tardis/simulation/base.py", line 8, in <module>
    from tardis.montecarlo import MontecarloRunner
  File "/Users/sacredmi/anaconda3/envs/tardis/lib/python3.6/site-packages/tardis/montecarlo/__init__.py", line 1, in <module>
    from tardis.montecarlo.base import *
  File "/Users/sacredmi/anaconda3/envs/tardis/lib/python3.6/site-packages/tardis/montecarlo/base.py", line 13, in <module>
    from tardis.montecarlo import montecarlo, packet_source
  File "__init__.pxd", line 918, in init tardis.montecarlo.montecarlo
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
```

**Comment by SylviaObserver** [comment]
Could you please tell me specificly which numpy version is compatible with TARDIS? I've tried numpy==1.13 1.14 and 1.15 but all failed...

**Comment by jordi5** [comment]
Hi! Tardis works with numpy 1.15. Can you try to run the code in a Jupyter Notebook instead of the python terminal?

**Comment by jordi5** [comment]
@SylviaObserver could you solve the issue?

**Comment by wkerzendorf** [comment]
This will be closed after 8th of July 2020 if no activity has been recorded
