### ISSUE TITLE
Installation troubles with conda-forge

### ISSUE THREAD

**Issue by jamesgillanders** [tardis-sn/tardis#2209]
**Describe the bug**
The suggested installation instructions (available here: https://tardis-sn.github.io/tardis/installation.html; steps 1,2,3a) do not produce a working TARDIS install on my laptop (M1 MacBook Pro, running Venture 13.0.1), and conda version 22.11.1.

**To Reproduce**
Run the standard installation commands:

wget -q https://github.com/tardis-sn/tardis/releases/latest/download/conda-osx-64.lock
conda create --name tardis --file conda-osx-64.lock
conda activate tardis
conda install tardis-sn --channel conda-forge --no-deps

This produces the attached error message.

**Screenshots**

**System**
 - OS:
    - [ ] GNU/Linux
    - [*] macOS

 - Environment (`conda list`):
N /A

**Additional context**
Seems to be resolvable with the following steps (but by no means is this a best approach -- it just happened to quickly get me a working install):

conda create -n tardis_mamba
conda activate tardis_mamba
conda config --add channels conda-forge
conda install python=3.8
mamba install tardis-sn=2023
conda install h5py=2

[error_report_james_gillanders.txt](https://github.com/tardis-sn/tardis/files/10722296/error_report_james_gillanders.txt)

**Comment by epassaro** [comment]
Hi James!

I reproduced your bug in Linux. These are my observations:

- This does not happen when using `mamba` (which uses a smarter dependency solver) instead of `conda`
- The `.lock` file is produced by `conda-lock` on the CI pipeline, so it should be consistent enough for `conda`. I'll open an issue in conda-lock repository
- Sadly, there's no way to "force install" a package ignoring its dependencies (or just skipping the solver step). The `--force` flag does not work in that way: https://github.com/conda/conda/issues/2980

I think we should wait to the next release and see if the new lockfile solves the issue.

**Comment by andrewfullard** [comment]
New release is out, please test again

**Comment by jamesgillanders** [comment]
The issue persists, even with the new lockfile -- error message is (as far I can tell) identical to the one posted above.

**Comment by atharva-2001** [comment]
@light2802 and I are getting the same issue- I created a new env and tried installing it via conda and it fails. Same error message as James

**Comment by wkerzendorf** [comment]
@epassaro ?

**Comment by epassaro** [comment]
@atharva-2001 which platform are you and @light2802 using

**Comment by light2802** [comment]
Im using linux

**Comment by epassaro** [comment]
I get:

```
Collecting package metadata (current_repodata.json): done
Solving environment: \ 
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - conda-forge/linux-64::sqlite==3.40.0=h4ff8645_0
  - conda-forge/noarch::_ipython_minor_entry_point==8.7.0=h3b92ee0_0
  - conda-forge/linux-64::jpeg==9e=h0b41bf4_3
failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/mambaforge/lib/python3.10/site-packages/conda/exceptions.py", line 1124, in __call__
        return func(*args, **kwargs)
      File "/opt/mambaforge/lib/python3.10/site-packages/conda/cli/main.py", line 69, in main_subshell
        exit_code = do_call(args, p)
      File "/opt/mambaforge/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 91, in do_call
        return getattr(module, func_name)(args, parser)
      File "/opt/mambaforge/lib/python3.10/site-packages/conda/notices/core.py", line 109, in wrapper
        return func(*args, **kwargs)
      File "/opt/mambaforge/lib/python3.10/site-packages/conda/cli/main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "/opt/mambaforge/lib/python3.10/site-packages/conda/cli/install.py", line 264, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/opt/mambaforge/lib/python3.10/site-packages/conda/core/solve.py", line 132, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "/opt/mambaforge/lib/python3.10/site-packages/conda/core/solve.py", line 175, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "/opt/mambaforge/lib/python3.10/site-packages/conda/core/solve.py", line 280, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/opt/mambaforge/lib/python3.10/site-packages/conda/common/io.py", line 84, in decorated
        return f(*args, **kwds)
      File "/opt/mambaforge/lib/python3.10/site-packages/conda/core/solve.py", line 447, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/opt/mambaforge/lib/python3.10/site-packages/conda/core/solve.py", line 1060, in _prepare
        reduced_index = get_reduced_index(self.prefix, self.channels,
      File "/opt/mambaforge/lib/python3.10/site-packages/conda/core/index.py", line 270, in get_reduced_index
        push_record(record)
      File "/opt/mambaforge/lib/python3.10/site-packages/conda/core/index.py", line 244, in push_record
        combined_depends = record.combined_depends
      File "/opt/mambaforge/lib/python3.10/site-packages/conda/models/records.py", line 338, in combined_depends
        result = {ms.name: ms for ms in MatchSpec.merge(self.depends)}
      File "/opt/mambaforge/lib/python3.10/site-packages/conda/models/match_spec.py", line 478, in merge
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "/opt/mambaforge/lib/python3.10/site-packages/conda/models/match_spec.py", line 478, in <lambda>
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "/opt/mambaforge/lib/python3.10/site-packages/conda/models/match_spec.py", line 509, in _merge
        final = this_component.merge(that_component)
      File "/opt/mambaforge/lib/python3.10/site-packages/conda/models/match_spec.py", line 785, in merge
        raise ValueError("Incompatible component merge:\n  - %r\n  - %r"
    ValueError: Incompatible component merge:
      - 'mpi_mpich_*'
      - 'mpi_mpich_tempest*'

`$ /opt/mambaforge/bin/conda install -c conda-forge tardis-sn --no-deps`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=tardis-forge
                CONDA_EXE=/opt/mambaforge/bin/conda
             CONDA_PREFIX=/home/epassaro/.conda/envs/tardis-forge
    CONDA_PROMPT_MODIFIER=(tardis-forge)
         CONDA_PYTHON_EXE=/opt/mambaforge/bin/python
               CONDA_ROOT=/opt/mambaforge
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                 GDL_PATH=+/usr/share/gnudatalanguage
               LD_PRELOAD=<not set>
                  MANPATH=/usr/local/man:/usr/share/man
             MOZ_GMP_PATH=/usr/lib64/mozilla/plugins/gmp-gmpopenh264/system-installed
                     PATH=/home/epassaro/.conda/envs/tardis-forge/bin:/home/epassaro/go:/home/ep
                          assaro/.local/bin:/opt/wine/wine-6.23-staging-amd64/bin:/opt/mambaforg
                          e/condabin:/home/epassaro/go:/home/epassaro/.local/bin:/home/epassaro/
                          .local/bin:/home/epassaro/bin:/usr/local/bin:/usr/bin:/bin
            PYTHONSTARTUP=/etc/pythonstart
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
            XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
         XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1
                 XNLSPATH=/usr/share/X11/nls

     active environment : tardis-forge
    active env location : /home/epassaro/.conda/envs/tardis-forge
            shell level : 1
       user config file : /home/epassaro/.condarc
 populated config files : /opt/mambaforge/.condarc
                          /home/epassaro/.condarc
          conda version : 23.1.0
    conda-build version : not installed
         python version : 3.10.10.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.37=0
                          __linux=6.3.7=0
                          __unix=0=0
       base environment : /opt/mambaforge  (read only)
      conda av data dir : /opt/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /opt/mambaforge/pkgs
                          /home/epassaro/.conda/pkgs
       envs directories : /home/epassaro/.conda/envs
                          /opt/mambaforge/envs
               platform : linux-64
             user-agent : conda/23.1.0 requests/2.28.2 CPython/3.10.10 Linux/6.3.7-1-default opensuse-tumbleweed/20230619 glibc/2.37
                UID:GID : 1000:100
             netrc file : /home/epassaro/.netrc
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: 
Timeout reached. No report sent.
```

This happens because the dependencies in the `tardis` environment are becoming old and the `conda` package manager is not-so-smart and can't handle them. 

The package can be installed using `mamba` or [using conda with the `libamamba` solver](https://www.anaconda.com/blog/a-faster-conda-for-a-growing-community) without problems. 

If you don't want to do that you could just checkout your TARDIS repository to the desired release and run `pip install .`


--- 
What can we do on our side?

- As I said before, the ideal solution would be to force conda to not solve packages, but this can't be done because conda developers have strange ideas
- Pin or unpin dependencies to alleviate conda dependency solving step
- Add `tardis-sn` to the lockfiles (I don't like this, would be confusing for some people)
- avoid conda-forge for the reproducible/deterministic installation (there are a lot of ways of doing this)

**Comment by pmricker** [comment]
Also seeing the above error under CentOS 7.9, conda 23.5.0.

**Comment by andrewfullard** [comment]
Is this resolved using the lock files?

**Comment by andrewfullard** [comment]
`libmamba` is now the default conda solver, so this should be resolved. Please reopen if not.
