### ISSUE TITLE
ModuleNotFoundError: No module named 'tardis.energy_input'

### ISSUE THREAD

**Issue by yun201720** [tardis-sn/tardis#2370]
Iterations:                                                                    Traceback (most recent call last):                                               
  File "ppTardis.py", line 5, in <module>
    from tardis import run_tardis
  File "/home/xiangyun/anaconda3/envs/tardis/lib/python3.8/site-packages/tardis-2023.7.23.1.dev1+g64404836d-py3.8.egg/tardis/__init__.py", line 26, in <module>
    from tardis.io.util import yaml_load_file as yaml_load
  File "/home/xiangyun/anaconda3/envs/tardis/lib/python3.8/site-packages/tardis-2023.7.23.1.dev1+g64404836d-py3.8.egg/tardis/io/__init__.py", line 6, in <module>
    from tardis.io.model_reader import (
  File "/home/xiangyun/anaconda3/envs/tardis/lib/python3.8/site-packages/tardis-2023.7.23.1.dev1+g64404836d-py3.8.egg/tardis/io/model_reader.py", line 4, in <module>
    from tardis.montecarlo.base import MontecarloTransport
  File "/home/xiangyun/anaconda3/envs/tardis/lib/python3.8/site-packages/tardis-2023.7.23.1.dev1+g64404836d-py3.8.egg/tardis/montecarlo/__init__.py", line 10, in <module>
    from tardis.montecarlo.base import *
  File "/home/xiangyun/anaconda3/envs/tardis/lib/python3.8/site-packages/tardis-2023.7.23.1.dev1+g64404836d-py3.8.egg/tardis/montecarlo/base.py", line 17, in <module>
    from tardis.montecarlo.montecarlo_numba.formal_integral import FormalIntegrator
  File "/home/xiangyun/anaconda3/envs/tardis/lib/python3.8/site-packages/tardis-2023.7.23.1.dev1+g64404836d-py3.8.egg/tardis/montecarlo/montecarlo_numba/__init__.py", line 16, in <module>
    from tardis.montecarlo.montecarlo_numba.base import montecarlo_radial1d
  File "/home/xiangyun/anaconda3/envs/tardis/lib/python3.8/site-packages/tardis-2023.7.23.1.dev1+g64404836d-py3.8.egg/tardis/montecarlo/montecarlo_numba/base.py", line 27, in <module>
    from tardis.montecarlo.montecarlo_numba.single_packet_loop import (
  File "/home/xiangyun/anaconda3/envs/tardis/lib/python3.8/site-packages/tardis-2023.7.23.1.dev1+g64404836d-py3.8.egg/tardis/montecarlo/montecarlo_numba/single_packet_loop.py", line 6, in <module>
    from tardis.transport.r_packet_transport import (
  File "/home/xiangyun/anaconda3/envs/tardis/lib/python3.8/site-packages/tardis-2023.7.23.1.dev1+g64404836d-py3.8.egg/tardis/transport/r_packet_transport.py", line 19, in <module>
    from tardis.montecarlo.montecarlo_numba.opacities import calculate_tau_electron
  File "/home/xiangyun/anaconda3/envs/tardis/lib/python3.8/site-packages/tardis-2023.7.23.1.dev1+g64404836d-py3.8.egg/tardis/montecarlo/montecarlo_numba/opacities.py", line 12, in <module>
    from tardis.energy_input.util import kappa_calculation
ModuleNotFoundError: No module named 'tardis.energy_input'

**Comment by wkerzendorf** [comment]
Can you give us a bit more information
