### ISSUE TITLE
Unable to run tardis

### ISSUE THREAD

**Issue by officialasishkumar** [tardis-sn/tardis#2537]
**Describe the bug** 
I was trying to run tardis with memory profiler but I am getting an error. 
```
Traceback (most recent call last):
  File "/home/charon/coding/random/profilers-test/memray/test1-without-changes/main.py", line 1, in <module>
    from tardis import run_tardis
  File "/home/charon/.local/lib/python3.10/site-packages/tardis/__init__.py", line 33, in <module>
    gi.require_version('GooCanvas', '2.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GooCanvas not available
```

**To Reproduce**
```
from tardis import run_tardis

sim = run_tardis("tardis_example.yml",
                 virtual_packet_logging=True,
                 show_convergence_plots=True,
                 export_convergence_plots=True,
                 log_level="INFO")

# scalene --memory --reduced-profile main.py

```
I ran this main.py file with scalene and I am getting an error. Here is `python3.10/site-packages/tardis/__init__.py`:
https://paste.opensuse.org/pastes/6affe585fbdb

**Screenshots**

**System**
 - OS:
    - [x] GNU/Linux
    - [ ] macOS

 - Environment (`conda list`):
 ```
 tardis                    2024.3.7.0.dev2+gda6cf580.d20240310           dev_0    <develop>
 ```

**Additional context**

**Comment by andrewfullard** [comment]
`ValueError: Namespace GooCanvas not available` is not a TARDIS problem.
