### ISSUE TITLE
ValueError while running the example given in the QuickStart Guide

### ISSUE THREAD

**Issue by ayushjain19** [tardis-sn/tardis#684]
Hi! I am new to Tardis. I was trying to run an example which is given in the [QuickStart Guide](http://tardis.readthedocs.io/en/latest/running.html).

The example directory with the configuration file can be found [here](http://opensupernova.org/~ftsamis/tardis_example.tar.gz).

When I run the command `tardis tardis_example.yml output_spectrum.dat`, I get the following error:

```
$ tardis tardis_example.yml output_spectrum.dat
tardis.plasma.standard_plasmas - INFO - Reading Atomic Data from kurucz_cd23_chianti_H_He.h5
tardis.atomic - INFO - Read Atom Data with UUID=5ca3035ca8b311e3bb684437e69d75d7 and MD5=21095dd25faa1683f4c90c911a00c3f8
Traceback (most recent call last):
  File "/usr/local/bin/tardis", line 5, in <module>
    pkg_resources.run_script('tardis-sn==1.5.dev2631', u'tardis')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/tardis_sn-1.5.dev2631-py2.7-linux-x86_64.egg/EGG-INFO/scripts/tardis", line 65, in <module>
    simulation = Simulation.from_config(tardis_config)
  File "/usr/local/lib/python2.7/dist-packages/tardis_sn-1.5.dev2631-py2.7-linux-x86_64.egg/tardis/simulation/base.py", line 379, in from_config
    atom_data=kwargs.get('atom_data', None))
  File "/usr/local/lib/python2.7/dist-packages/tardis_sn-1.5.dev2631-py2.7-linux-x86_64.egg/tardis/plasma/standard_plasmas.py", line 153, in assemble_plasma
    property_kwargs=property_kwargs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tardis_sn-1.5.dev2631-py2.7-linux-x86_64.egg/tardis/plasma/base.py", line 24, in __init__
    self.update(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tardis_sn-1.5.dev2631-py2.7-linux-x86_64.egg/tardis/plasma/base.py", line 158, in update
    self.plasma_properties_dict[module_name].update()
  File "/usr/local/lib/python2.7/dist-packages/tardis_sn-1.5.dev2631-py2.7-linux-x86_64.egg/tardis/plasma/properties/base.py", line 126, in update
    *self._get_input_values()))
  File "/usr/local/lib/python2.7/dist-packages/tardis_sn-1.5.dev2631-py2.7-linux-x86_64.egg/tardis/plasma/properties/ion_population.py", line 55, in calculate
    phis[start_id - i:end_id - i - 1] = current_phis
ValueError: could not broadcast input array from shape (93,20) into shape (88,20)

```
 
Moreover on running the command `tardis.__githash__` in Python shell, I get the following result:

```
>>> import tardis
>>> tardis.__githash__
u'b77b9e142e5562ea24ae173f8edcef756fa49886'
```

Any insights?

**Comment by wkerzendorf** [comment]
@ftsamis problem in the new components?

**Comment by ftsamis** [comment]
@ayushjain19 I can't reproduce this. Are you sure you are running the tardis_example file you linked?

**Steps taken:**
I created a new fresh environment following step-by-step the instructions at: http://tardis.readthedocs.io/en/latest/installation.html#installing-tardis-with-anaconda-recommended (with the development tardis version) and also followed step-by-step the quickstart instructions at: http://tardis.readthedocs.io/en/latest/running.html#running-tardis-in-the-commandline. TARDIS runs as expected, successfully  finishing all 20 iterations.

**Comment by ftsamis** [comment]
@ayushjain19 As I told you in gitter, it seems you are not inside a conda environment, which means you probably have different library versions installed than those TARDIS requires.

Please paste the output of this command:
`python -c "import numpy, pandas; print 'np:', numpy.__version__; print 'pd:', pandas.__version__"`

**Comment by yeganer** [comment]
@ayushjain19 Another thing would be running the tardis test suit on your system and see if the tests pass and if not, which ones fail.

**Comment by ayushjain19** [comment]
OK. So, I researched to some extent. I am using **virtualenv**, and not conda environment. 
1. Initially, some libraries were installed globally on my system and not in virtualenv which may have accounted to that error.

2. Now, I have installed the libraries in virtualenv and the result to the command `python -c "import numpy, pandas; print 'np:', numpy.__version__; print 'pd:', pandas.__version__"`  is:

```
(tardis)ayush@Ayush-19:~/Tardis/tardis_example$ python -c "import numpy, pandas; print 'np:', numpy.__version__; print 'pd:', pandas.__version__"
np: 1.11.3
pd: 0.19.1
```

3. Now, when I try running the command `tardis tardis_example.yml output_spectrum.dat`, I get the following:

```
(tardis)ayush@Ayush-19:~/Tardis/tardis_example$ tardis tardis_example.yml output_spectrum.dat
Traceback (most recent call last):
  File "/home/ayush/.virtualenvs/tardis/bin/tardis", line 62, in <module>
    tardis_config = config_reader.Configuration.from_yaml(args.config_fname)
  File "/home/ayush/.virtualenvs/tardis/local/lib/python2.7/site-packages/tardis/io/config_reader.py", line 784, in from_yaml
    return cls.from_config_dict(yaml_dict, test_parser=test_parser)
  File "/home/ayush/.virtualenvs/tardis/local/lib/python2.7/site-packages/tardis/io/config_reader.py", line 828, in from_config_dict
    config_dict).get_config()
  File "/home/ayush/.virtualenvs/tardis/local/lib/python2.7/site-packages/tardis/io/config_validator.py", line 1161, in __init__
    self.__parse_config(configuration_definition, input_configuration)
  File "/home/ayush/.virtualenvs/tardis/local/lib/python2.7/site-packages/tardis/io/config_validator.py", line 1337, in __parse_config
    self.__conf_o, self.__conf_v = recursive_parser(default_configuration, configuration, [])
  File "/home/ayush/.virtualenvs/tardis/local/lib/python2.7/site-packages/tardis/io/config_validator.py", line 1323, in recursive_parser
    tmp_conf_ob[k], tmp_conf_val[k] = recursive_parser(v, configuration, path + [k])
  File "/home/ayush/.virtualenvs/tardis/local/lib/python2.7/site-packages/tardis/io/config_validator.py", line 1323, in recursive_parser
    tmp_conf_ob[k], tmp_conf_val[k] = recursive_parser(v, configuration, path + [k])
  File "/home/ayush/.virtualenvs/tardis/local/lib/python2.7/site-packages/tardis/io/config_validator.py", line 1309, in recursive_parser
    ccontainer = Container(top_default, container_conf, container_path=path)
  File "/home/ayush/.virtualenvs/tardis/local/lib/python2.7/site-packages/tardis/io/config_validator.py", line 997, in __init__
    raise ValueError('Entry %s is missing in configuration. [%s]' % (str(nitem), self.__container_path))
ValueError: Entry hold-iterations is missing in configuration. [['montecarlo', 'convergence_strategy']]

```

4. PS: I am running the tardis_example file that I linked. It is the same file which is there in the [QuickStart Guide](http://tardis.readthedocs.io/en/latest/running.html) with name **example directory**.

5. Adding to all this, I noticed one thing that 6th point in [http://tardis.readthedocs.io/en/latest/workflow/python_environment.html](http://tardis.readthedocs.io/en/latest/workflow/python_environment.html) contains a link in the command 
```
$ pip install -r https://raw.githubusercontent.com/tardis-sn/tardis/master/pip-requirements
```
 which should have all the recommended packages. Instead, that [link](https://raw.githubusercontent.com/tardis-sn/tardis/master/pip-requirements) gives 404 error. 
If I am correct here that, that link should contain all the recommended packages, maybe I don't have all those recommended packages as the above command obviously installs nothing.

**Comment by ftsamis** [comment]
You get this error because you somehow switched to an older version of TARDIS. Reinstall TARDIS in your environment using the development version.

`pip install git+https://github.com/tardis-sn/tardis`

**Comment by ftsamis** [comment]
Also, it seems to me that the first time you didn't run tardis in either virtualenv or conda while in your last comment it's clear that you used virtualenv.

**Comment by ayushjain19** [comment]
Its done! The example ran successfully. Thanks a lot @ftsamis @yeganer @wkerzendorf  for guiding me through.
