### ISSUE TITLE
Update tardis/docs/atomic/atomic_data_description.rst

### ISSUE THREAD

**Issue by yeganer** [tardis-sn/tardis#787]
With the changes that will be introduced in #786 the documentation should be updated accordingly.

**Comment by pfreddy** [comment]
I've just reinstalled TARDIS according to the recent documentation and a new error appeared while reading the atomic data from kurucz*.h5 file. Is it related to this issue?

file:///home/barna/error_message

**Comment by pfreddy** [comment]
I've just reinstalled TARDIS according to the recent documentation and a new error appeared while reading the atomic data from kurucz*.h5 file. Is it related to this issue?

**Comment by pfreddy** [comment]
I've just reinstalled TARDIS according to the recent documentation and a new error appeared while reading the atomic data from kurucz*.h5 file. Is it related to this issue?

tardis.plasma.standard_plasmas - INFO - Reading Atomic Data from kurucz_cd23_chianti_H_He.h5
Traceback (most recent call last):
  File "/home/barna/anaconda2/envs/tardis/bin/tardis", line 67, in <module>
    simulation = Simulation.from_config(tardis_config)
  File "/home/barna/anaconda2/envs/tardis/lib/python2.7/site-packages/tardis/simulation/base.py", line 353, in from_config
    atom_data=kwargs.get('atom_data', None))
  File "/home/barna/anaconda2/envs/tardis/lib/python2.7/site-packages/tardis/plasma/standard_plasmas.py", line 76, in assemble_plasma
    atom_data = atomic.AtomData.from_hdf(atom_data_fname)
  File "/home/barna/anaconda2/envs/tardis/lib/python2.7/site-packages/tardis/io/atomic.py", line 148, in from_hdf
    dataframes[name] = store[name]
  File "/home/barna/anaconda2/envs/tardis/lib/python2.7/site-packages/pandas/io/pytables.py", line 479, in __getitem__
    return self.get(key)
  File "/home/barna/anaconda2/envs/tardis/lib/python2.7/site-packages/pandas/io/pytables.py", line 696, in get
    return self._read_group(group)
  File "/home/barna/anaconda2/envs/tardis/lib/python2.7/site-packages/pandas/io/pytables.py", line 1339, in _read_group
    s = self._create_storer(group)
  File "/home/barna/anaconda2/envs/tardis/lib/python2.7/site-packages/pandas/io/pytables.py", line 1222, in _create_storer
    "cannot create a storer if the object is not existing "
TypeError: cannot create a storer if the object is not existing nor a value are passed

**Comment by wkerzendorf** [comment]
@pfreddy the old atomic datafiles do not work anymore - you need to get the new ones from https://github.com/tardis-sn/tardis-refdata/tree/master/atom_data

**Comment by unoebauer** [comment]
Closing in favour of a aggregate documentation issue
