### ISSUE TITLE
TypeError when running Quickstart Guide

### ISSUE THREAD

**Issue by laudb** [tardis-sn/tardis#798]
Hi guys,
 I tried running TARDIS using the Quickstart Guide after following Installation instructions in the [docs](http://tardis.readthedocs.io/en/latest/installation.html) and had this error:
 TypeError: cannot create a storer if the object is not existing nor a value are passed

`(tardis) eit@eit-HP-Pavilion-TS-15-Notebook-PC:~/DEV/ASTRO/latest/tardis_example$ tardis tardis_example.yml output_spectrum.dat

[tardis.plasma.standard_plasmas][INFO   ]  Reading Atomic Data from kurucz_cd23_chianti_H_He.h5 (standard_plasmas.py:75)
tardis.plasma.standard_plasmas - INFO - Reading Atomic Data from kurucz_cd23_chianti_H_He.h5
Traceback (most recent call last):
  File "/home/eit/anaconda/envs/tardis/bin/tardis", line 67, in <module>
    simulation = Simulation.from_config(tardis_config)
  File "/home/eit/anaconda/envs/tardis/lib/python2.7/site-packages/tardis/simulation/base.py", line 353, in from_config
    atom_data=kwargs.get('atom_data', None))
  File "/home/eit/anaconda/envs/tardis/lib/python2.7/site-packages/tardis/plasma/standard_plasmas.py", line 76, in assemble_plasma
    atom_data = atomic.AtomData.from_hdf(atom_data_fname)
  File "/home/eit/anaconda/envs/tardis/lib/python2.7/site-packages/tardis/io/atomic.py", line 148, in from_hdf
    dataframes[name] = store[name]
  File "/home/eit/anaconda/envs/tardis/lib/python2.7/site-packages/pandas/io/pytables.py", line 479, in __getitem__
    return self.get(key)
  File "/home/eit/anaconda/envs/tardis/lib/python2.7/site-packages/pandas/io/pytables.py", line 696, in get
    return self._read_group(group)
  File "/home/eit/anaconda/envs/tardis/lib/python2.7/site-packages/pandas/io/pytables.py", line 1339, in _read_group
    s = self._create_storer(group)
  File "/home/eit/anaconda/envs/tardis/lib/python2.7/site-packages/pandas/io/pytables.py", line 1222, in _create_storer
    "cannot create a storer if the object is not existing "
TypeError: cannot create a storer if the object is not existing nor a value are passed`

I thought I did something wrong but after repeating the steps a couple of times I had the same error, is there something I'm missing?

**Comment by pfreddy** [comment]
There are a new configuration for the atomic database. The new atomic data file can be found here:
https://github.com/tardis-sn/tardis-refdata/tree/master/atom_data

I met the same problem before. (see #787).

**Comment by laudb** [comment]
Yes, it's the same as #787, It worked after I used the new configuration for the atomic database, got my output_spectrum.dat was able to proceed further, thanks @pfreddy!
