### ISSUE TITLE
Cannot Import "motecarlo" package

### ISSUE THREAD

**Issue by manolis07gr** [tardis-sn/tardis#976]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here

```
#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

#### Expected Output

**Comment by manolis07gr** [comment]
Hi all,

I am back in using TARDIS after a while and wow, lots has changed! I am trying everything from the beginning and I am simply trying to reproduce the results of the Quickstart guide. However, when I do "sim = run_tardis('tardis_example.yml') I get the following package import error. Any help would be appreciated.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/macbro/Desktop/tardis/tardis/base.py", line 24, in run_tardis
    from tardis.simulation import Simulation
  File "/Users/macbro/Desktop/tardis/tardis/simulation/__init__.py", line 1, in <module>
    from tardis.simulation.base import Simulation
  File "/Users/macbro/Desktop/tardis/tardis/simulation/base.py", line 8, in <module>
    from tardis.montecarlo import MontecarloRunner
  File "/Users/macbro/Desktop/tardis/tardis/montecarlo/__init__.py", line 1, in <module>
    from tardis.montecarlo.base import *
  File "/Users/macbro/Desktop/tardis/tardis/montecarlo/base.py", line 13, in <module>
    from tardis.montecarlo import montecarlo, packet_source
ImportError: cannot import name 'montecarlo'

**Comment by manolis07gr** [comment]
Any Ideas yet?

**Comment by chvogl** [comment]
Hi @manolis07gr. How did you install TARDIS: via pip or did you clone it from github?
It also seems like you are not using the recommended TARDIS conda environment.

**Comment by manolis07gr** [comment]
Hi @chvogl, I fixed this installation/environment problem - but now I see another error when I run the Quickstart example - similar to that described by another user:

Traceback (most recent call last):
  File "example.py", line 6, in <module>
    sim = run_tardis('tardis_example.yml')
  File "/anaconda3/envs/tardis/lib/python3.6/site-packages/tardis_sn-3.0.dev3356-py3.6-macosx-10.9-x86_64.egg/tardis/base.py", line 37, in run_tardis
    simulation = Simulation.from_config(tardis_config, atom_data=atom_data)
  File "/anaconda3/envs/tardis/lib/python3.6/site-packages/tardis_sn-3.0.dev3356-py3.6-macosx-10.9-x86_64.egg/tardis/simulation/base.py", line 440, in from_config
    atom_data=kwargs.get('atom_data', None))
  File "/anaconda3/envs/tardis/lib/python3.6/site-packages/tardis_sn-3.0.dev3356-py3.6-macosx-10.9-x86_64.egg/tardis/plasma/standard_plasmas.py", line 77, in assemble_plasma
    atom_data = AtomData.from_hdf(atom_data_fname)
  File "/anaconda3/envs/tardis/lib/python3.6/site-packages/tardis_sn-3.0.dev3356-py3.6-macosx-10.9-x86_64.egg/tardis/io/atom_data/base.py", line 159, in from_hdf
    dataframes[name] = store[name]
  File "/anaconda3/envs/tardis/lib/python3.6/site-packages/pandas/io/pytables.py", line 504, in __getitem__
    return self.get(key)
  File "/anaconda3/envs/tardis/lib/python3.6/site-packages/pandas/io/pytables.py", line 695, in get
    return self._read_group(group)
  File "/anaconda3/envs/tardis/lib/python3.6/site-packages/pandas/io/pytables.py", line 1423, in _read_group
    return s.read(**kwargs)
  File "/anaconda3/envs/tardis/lib/python3.6/site-packages/pandas/io/pytables.py", line 2995, in read
    start=_start, stop=_stop)
  File "/anaconda3/envs/tardis/lib/python3.6/site-packages/pandas/io/pytables.py", line 2540, in read_array
    ret = node[0][start:stop]
  File "/anaconda3/envs/tardis/lib/python3.6/site-packages/tables/vlarray.py", line 681, in __getitem__
    return self.read(start, stop, step)[0]
  File "/anaconda3/envs/tardis/lib/python3.6/site-packages/tables/vlarray.py", line 821, in read
    listarr = self._read_array(start, stop, step)
  File "tables/hdf5extension.pyx", line 2155, in tables.hdf5extension.VLArray._read_array
ValueError: cannot set WRITEABLE flag to True of this array

Any Ideas there? One step closer...

**Comment by chvogl** [comment]
This seems to be the same problem as described in #977. I will tentatively close this issue, since the original build problem is fixed, and we can continue the discussion in #977.
